/**
 * Solar energy totals for a single day.
 */
export interface DailySolarSummary {
  /** Total energy generated by the solar array, in kWh. */
  readonly generatedKwh: number
}

/**
 * Battery energy totals for a single day.
 */
export interface DailyBatterySummary {
  /** Total energy stored into the battery over the day, in kWh. */
  readonly chargedKwh: number
  /** Total energy drawn from the battery over the day, in kWh. */
  readonly dischargedKwh: number
}

/**
 * Grid energy totals for a single day.
 */
export interface DailyGridSummary {
  /** Total energy imported from the grid over the day, in kWh. */
  readonly importedKwh: number
  /** Total energy exported to the grid over the day, in kWh. */
  readonly exportedKwh: number
}

/**
 * Home consumption totals for a single day.
 */
export interface DailyHomeSummary {
  /** Total energy consumed by the home over the day, in kWh. */
  readonly consumedKwh: number
}

/**
 * A summary of the home's energy activity for a single day.
 *
 * Contains raw accumulated energy quantities in kWh. These values come
 * directly from the provider and represent what happened on a given day.
 *
 * Financial outcomes (cost, savings, earnings) are derived separately by
 * packages/core and stored in DailyFinancials, because they depend on
 * tariff rates that may not always be available.
 */
export interface DailySummary {
  /** The calendar date this summary covers. */
  readonly date: Date
  /** Solar generation totals. */
  readonly solar: DailySolarSummary
  /** Battery charge and discharge totals. */
  readonly battery: DailyBatterySummary
  /** Grid import and export totals. */
  readonly grid: DailyGridSummary
  /** Home consumption totals. */
  readonly home: DailyHomeSummary
}

/**
 * Financial outcomes derived from a DailySummary.
 *
 * Produced by packages/core using DailySummary kWh values and the
 * configured import and export tariff rates. Stored alongside DailySummary
 * in the Pinia store, but kept separate because tariff data may not be
 * configured or available for every installation.
 */
export interface DailyFinancials {
  /** The calendar date these financials cover. */
  readonly date: Date
  /**
   * The cost of electricity imported from the grid.
   * Calculated as: importedKwh × importRate.
   */
  readonly importCost: number
  /**
   * Earnings from electricity exported to the grid.
   * Calculated as: exportedKwh × exportRate.
   */
  readonly exportEarnings: number
  /**
   * Estimated saving compared to running the home without solar or battery.
   * Calculated as: (consumedKwh × importRate) − importCost + exportEarnings.
   *
   * Represents what the electricity bill would have been minus what was
   * actually paid, plus what was earned from export.
   */
  readonly savings: number
  /**
   * ISO 4217 currency code for all monetary values in this object.
   * @example 'GBP'
   */
  readonly currency: string
}
