/**
 * Identifies the type of energy state an insight describes.
 *
 * Used by the UI to select icons, animations, and colour themes. Each member
 * corresponds to a distinct mode of home energy operation.
 *
 * - `battery_charging_solar`  Battery is receiving charge from surplus solar.
 * - `battery_charging_grid`   Battery is charging from the grid (e.g. overnight off-peak).
 * - `battery_discharging`     Battery is supplying power to the home, reducing grid draw.
 * - `solar_exporting`         Solar generation exceeds home demand; surplus is exported.
 * - `solar_covering`          Solar is meeting all home demand without battery or grid.
 * - `grid_importing`          The home is drawing power from the grid.
 * - `idle`                    No significant energy activity is occurring.
 */
export type InsightType =
  | 'battery_charging_solar'
  | 'battery_charging_grid'
  | 'battery_discharging'
  | 'solar_exporting'
  | 'solar_covering'
  | 'grid_importing'
  | 'idle'

/**
 * The emotional tone of an insight.
 *
 * Drives visual treatment in the UI — colour, icon weight, background.
 *
 * - `positive`  Good outcome: saving money, earning from export, self-sufficient.
 * - `neutral`   Normal operation; no action needed.
 * - `negative`  Attention warranted: high import cost, battery depleted, etc.
 */
export type InsightSentiment = 'positive' | 'neutral' | 'negative'

/**
 * How important this insight is relative to others.
 *
 * Used to sort and filter insights when multiple are present.
 *
 * - `high`    Requires attention or represents a significant event.
 * - `normal`  Standard operational insight; informational.
 * - `low`     Background context; safe to suppress in compact views.
 */
export type InsightPriority = 'high' | 'normal' | 'low'

/**
 * How certain Cardinal is about this insight.
 *
 * Reflects sensor availability and data quality at the time of generation.
 *
 * - `high`    All relevant sensors are present and returning valid data.
 * - `medium`  Some sensors are missing or data is partially estimated.
 * - `low`     Significant uncertainty; displayed with a qualifier.
 */
export type InsightConfidence = 'high' | 'medium' | 'low'

/**
 * A suggested action associated with an insight.
 *
 * Actions are informational in v1. Future versions may include service calls
 * or deep links into Home Assistant automations.
 */
export interface InsightAction {
  /** Short label for the action, suitable for a button or list item. */
  readonly label: string
  /** Optional explanation of what the action does or why it is suggested. */
  readonly description?: string
}

/**
 * A structured, human-readable explanation of something Cardinal has understood
 * about the home's energy state.
 *
 * EnergyInsight is the primary output of Cardinal's explanation engine. Insights
 * are generated by packages/core, held in Pinia stores, and rendered by the UI
 * as the "story" of the home.
 *
 * Design rules:
 * - The description must be understandable without any supporting numbers.
 * - Numbers and charts support the insight — they do not replace it.
 * - The description is always a complete sentence directed at the homeowner.
 * - The detail is omitted unless it genuinely adds information.
 * - Actions are only included when there is something meaningful to suggest.
 */
export interface EnergyInsight {
  /**
   * A unique identifier for this insight instance.
   *
   * Stable within a session. Used by the UI to key transition animations and
   * by consumers to deduplicate repeated insights of the same type.
   */
  readonly id: string

  /**
   * Identifies the mode of operation this insight describes.
   * Used for icon selection, UI transitions, and filtering.
   */
  readonly type: InsightType

  /**
   * The emotional tone of this insight.
   * Drives colour and visual styling in the UI.
   */
  readonly sentiment: InsightSentiment

  /**
   * How important this insight is. Used for sorting when multiple insights exist.
   */
  readonly priority: InsightPriority

  /**
   * How certain Cardinal is in this insight.
   * Reflected in the UI when confidence is below 'high'.
   */
  readonly confidence: InsightConfidence

  /**
   * When this insight was generated.
   *
   * Derived from the source EnergySnapshot's timestamp so it accurately
   * reflects when the energy state was observed, not when the object was built.
   */
  readonly timestamp: Date

  /**
   * A short label for the insight, suitable for compact displays, notifications,
   * and timeline entries.
   *
   * @example "Charging from Solar"
   * @example "Running on Solar"
   * @example "Grid Power"
   */
  readonly title: string

  /**
   * A full sentence describing what is happening, written in plain language
   * directed at the homeowner.
   *
   * This is the primary display string. It must be understandable on its own.
   *
   * @example "Your battery is charging from excess solar."
   * @example "Your home is running entirely on solar."
   * @example "Your home is running on grid power."
   */
  readonly description: string

  /**
   * Optional supporting context that enriches the description.
   *
   * Omit when it does not add meaningful information beyond the description.
   * Should never be required to understand the insight.
   *
   * @example "Battery is 76% full and rising."
   * @example "You've exported 4.2 kWh so far today."
   */
  readonly detail?: string

  /**
   * Optional actions the user could take in response to this insight.
   *
   * Informational in v1. Future versions may link to HA service calls
   * or automation controls.
   */
  readonly actions?: readonly InsightAction[]
}
