/**
 * Identifies the type of energy state an insight describes.
 *
 * Used by the UI to select appropriate icons, animations, and colour themes.
 * Each type corresponds to a distinct mode of home energy operation.
 *
 * - `battery_charging_solar`  Battery is receiving charge from surplus solar generation.
 * - `battery_charging_grid`   Battery is charging from the grid (e.g. overnight off-peak).
 * - `battery_discharging`     Battery is supplying power to the home, reducing grid draw.
 * - `solar_exporting`         Solar generation exceeds home demand; surplus is exported.
 * - `solar_covering`          Solar alone is meeting all home demand; no battery or grid needed.
 * - `grid_importing`          The home is drawing power from the grid.
 * - `idle`                    No significant energy activity is occurring.
 */
export type InsightType =
  | 'battery_charging_solar'
  | 'battery_charging_grid'
  | 'battery_discharging'
  | 'solar_exporting'
  | 'solar_covering'
  | 'grid_importing'
  | 'idle'

/**
 * The emotional tone of an insight.
 *
 * Drives the visual treatment of the insight in the UI (colour, icon style).
 *
 * - `positive`  Good news: saving money, earning from export, self-sufficient.
 * - `neutral`   Normal operation with no particular action needed.
 * - `negative`  Attention warranted: high import cost, battery depleted, etc.
 */
export type InsightSentiment = 'positive' | 'neutral' | 'negative'

/**
 * A human-readable explanation of the home's current energy state.
 *
 * EnergyInsight is the primary output of Cardinal's explanation engine.
 * It is generated by packages/core from an EnergySnapshot and is what
 * Cardinal presents to the user as the "story" of their home.
 *
 * Design rules:
 * - The headline must be understandable without any supporting numbers.
 * - Numbers and charts support the insight — they do not replace it.
 * - The headline is always a complete sentence directed at the homeowner.
 * - The detail is optional and should be omitted if it adds no value.
 */
export interface EnergyInsight {
  /**
   * Identifies the mode of operation this insight describes.
   * Used by the UI for icon selection and state transition animations.
   */
  readonly type: InsightType

  /**
   * A single sentence describing what is happening in plain language.
   *
   * @example "Your battery is charging from excess solar."
   * @example "Your home is running entirely on solar."
   * @example "Your home is running on grid power."
   */
  readonly headline: string

  /**
   * Optional supporting context that enriches the headline.
   * Omit when it does not add meaningful information beyond the headline.
   *
   * @example "Battery is 76% full and rising."
   * @example "You've exported 4.2 kWh so far today."
   */
  readonly detail?: string

  /**
   * The emotional tone of this insight.
   * Drives colour and visual styling in the UI.
   */
  readonly sentiment: InsightSentiment
}
