DOMAIN = "cardinal"
PANEL_URL = "cardinal"
PANEL_TITLE = "Cardinal"
PANEL_ICON = "mdi:sun-wireless-outline"
FRONTEND_DIR = "frontend"

CONF_SOLAR_POWER = "solar_power"
CONF_BATTERY_POWER = "battery_power"
CONF_BATTERY_CHARGE_POWER = "battery_charge_power"
CONF_BATTERY_DISCHARGE_POWER = "battery_discharge_power"
CONF_BATTERY_SOC = "battery_state_of_charge"
CONF_GRID_POWER = "grid_power"
CONF_GRID_IMPORT_POWER = "grid_import_power"
CONF_GRID_EXPORT_POWER = "grid_export_power"
CONF_HOME_CONSUMPTION = "home_consumption"
CONF_IMPORT_RATE = "import_rate"
CONF_EXPORT_RATE = "export_rate"
CONF_CURRENCY = "currency"
