export { default as NowPanel } from './components/NowPanel.vue'
export { default as TodayPanel } from './components/TodayPanel.vue'
export { default as DiagnosticsPanel } from './components/DiagnosticsPanel.vue'
export { default as InsightBlock } from './components/InsightBlock.vue'
export { default as LiveIndicator } from './components/LiveIndicator.vue'
export { default as MetricCard } from './components/MetricCard.vue'
export { default as TodayCard } from './components/TodayCard.vue'
export { default as FinancialSummary } from './components/FinancialSummary.vue'
export { default as SensorHealthBadge } from './components/SensorHealthBadge.vue'
export { default as SensorHealthOverlay } from './components/SensorHealthOverlay.vue'
export { default as EnergyFlowDiagram } from './components/EnergyFlowDiagram.vue'

export { useLastUpdated } from './composables/useLastUpdated.js'
export { energyIntensity } from './utils/energyIntensity.js'
export { useShowroomMode } from './composables/useShowroomMode.js'
export { useSimulationMode } from './composables/useSimulationMode.js'
export type { SimulationModeOptions } from './composables/useSimulationMode.js'
export { SHOWROOM_SCENES } from './showroom/scenes.js'
export type { ShowroomScene } from './showroom/scenes.js'
